---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: opa
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: opa
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: opa
    version: 1.12.0
